services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tuition-payment-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost
    networks:
      - app-network

  backend:
    build: 
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: tuition-payment-backend
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://admin:admin123@tuition-payment-mongodb:27017/ibanking_tuition?authSource=admin
      - DATABASE_NAME=ibanking_tuition
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=hoaianduong214@gmail.com
      - EMAIL_HOST_PASSWORD=aupw gycq ubpt ugxc
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - app-network
    depends_on:
      - mongodb
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:latest
    container_name: tuition-payment-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=ibanking_tuition
    ports:
      - "27017:27017"
    volumes:
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./database/users.json:/docker-entrypoint-initdb.d/users.json:ro
      - ./database/students.json:/docker-entrypoint-initdb.d/students.json:ro
      - ./database/transactions.json:/docker-entrypoint-initdb.d/transactions.json:ro
      - ./database/otp.json:/docker-entrypoint-initdb.d/otp.json:ro
      - mongodb_data:/data/db
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1G
    command: ["mongod", "--auth", "--wiredTigerCacheSizeGB", "0.5"]
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: tuition-payment-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
    command: redis-server --maxmemory 200mb --maxmemory-policy allkeys-lru
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: tuition-payment-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 128M
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

volumes:
  mongodb_data:
  redis_data:

networks:
  app-network:
    driver: bridge